language: java
sudo: required
jdk: openjdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  hosts:
    - api-itest.famifarm.fi
  sonarcloud:
    organization: "metatavu-oy"
  mariadb: '10.3'
  
install: true
    
before_script:
  - scripts/start-keycloak.sh

script:
  - . travis.sh

notifications:
  email: false
  webhooks:
    - http://travis.metatavu.io:7333/travisping
