language: java
sudo: required
jdk: openjdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  hosts:
    - api-itest.famifarm.fi
  sonarcloud:
    organization: "metatavu-oy"
  mariadb: '10.3'

install: true
    
before_script:
  - echo -e "[mysqld]\nlower-case-table-names = 1" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql -u root -e "show variables like 'lower%'"
  - mysql -u root < scripts/setup-db.sql
  - scripts/start-keycloak.sh

script:
  - . travis.sh

notifications:
  email: false
  webhooks:
    - http://travis.metatavu.io:7333/travisping
