package fi.metatavu.famifarm.reporting;

/**
 * Enum describing available reports
 * 
 * @author Antti Leppä
 */
public enum ReportType {

  XLS_EXAMPLE,
  WASTAGE,
  GROWTH_TIME,
  YIELD,
  PLANTING_YIELD,
  SOWED,
  PLANTED,
  SPREAD,
  HARVESTED,
  PACKED,
  PACKED_CAMPAINGS,
  PRODUCT_PHASE_COUNT,
  SEEDLING_TIME,
  SUMMARY,
  JUVA_PLANTING_LIST_REPORT,
  JUVA_HARVEST_LIST_REPORT,
  JUVA_PACKING_LIST_REPORT,
  JUVA_SOWING_SUMMARY_REPORT,
  JUVA_PLANTING_SUMMARY_REPORT,
  JUVA_PACKING_SUMMARY_REPORT,
  JUVA_HARVEST_SUMMARY_REPORT
}
